config/routes.rb
Rails.application.routes.draw do
  root 'homepage#show'
  resources :query_infos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/query_info.rb
class QueryInfo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show

  end
end

app/controllers/http_request_controller.rb
class HttpRequestController < ApplicationController
  def show
    @accesskey = ""
    @secretkey = "" + "&"
    Time.zone = "UTC"
    @time = Time.zone.now.strftime('%Y-%m-%dT%H:%M:%SZ')
    @hash = Hash.new
    @hash["SignatureMethod"] = "HMAC-SHA1"
    @hash["AccessKeyId"] = @accesskey
    @hash["SignatureVersion"] = "1.0"
    # @hash["Format"] = "XML"
    @hash["Timestamp"] = @time
    @hash["SignatureNonce"] = UUID.generate

    @hash["Action"] = "SendSms"
    @hash["Version"] = "2017-05-25"
    @hash["RegionId"] = "cn-hangzhou"
    @hash["PhoneNumbers"] = "15300000001"
    @hash["TemplateCode"] = "SMS_147201673"
    # @hash["TemplateParam"] = "{\"customer\":\"test\"}".encode("utf-8")
    # @hash["SignName"] = "阿里云短信测试专用".encode("utf-8")
    # @hash["OutId"] = "123"
    @hash = @hash.sort_by{|key, val|key}
    @final_params = ""
    @params = ""
    @hash.each do |hash1|
      @params += "&" + hash1[0] + "=" + hash1[1]
      @final_params += "&" + hash1[0] + "=" + hash1[1]
    end
    @params = @params[1, @params.length]
    @params = URI.escape(@params, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
    @pre_params = "GET&amp;%2F&amp;"
    @params = @pre_params + @params
    Rails::logger.info(@params)

    key = @secretkey.encode("utf-8")
    digest = OpenSSL::Digest.new('sha1')
    string_to_sign = @params.encode("utf-8")
    @hashed = Base64.encode64(OpenSSL::HMAC.digest(digest, key, string_to_sign))

    @final_params = URI.escape(@final_params, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]"))
    @final_params = @final_params.gsub("%3D", "=")
    @final_params = @final_params.gsub("%26", "&")
    @final_params =URI.escape(@hashed.chop, Regexp.new("[^#{URI::PATTERN::UNRESERVED}]")) + @final_params
    Rails::logger.info(@final_params)


    @url = "http://dysmsapi.aliyuncs.com/?Signature=" + @final_params
    request = Typhoeus::Request.new(
        @url,
        method: :get,
        )
    request.run
    @response = request.response
  end
end

app/controllers/query_infos_controller.rb
class QueryInfosController < ApplicationController
  def index
    @query_infos = QueryInfo.all
  end

  def create
    @que
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def webpack_javascripts_tag(name)
    filename = "#{name}.bundle.js"
    asset_url = Rails.application.config.asset_host
    src = "#{asset_url}/assets/#{filename}"

    if Rails.env.development?
    elsif Rails.configuration.webpack[:manifest]
      asset_name = Rails.configuration.webpack[:manifest]["#{name}.js?7.1.40"]
      if asset_name
        src = "#{asset_url}/assets/#{asset_name}"
      end
    end
    javascript_include_tag(src)
  end
end

# def javascript_include_tag(*sources)
#   options = sources.extract_options!.stringify_keys
#   path_options = options.extract!("protocol", "extname", "host", "skip_pipeline").symbolize_keys
#   sources.uniq.map { |source|
#     tag_options = {
#         "src" => path_to_javascript(source, path_options)
#     }.merge!(options)
#     content_tag("script".freeze, "", tag_options)
#   }.join("\n").html_safe
# end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/http_request_helper.rb
module HttpRequestHelper
end

app/helpers/query_infos_helper.rb
module QueryInfosHelper
end

app/views/homepage/_background.html.haml
.homepage_main
  .top_menu_container
    = render 'top_menu'
  .background_star_sky

app/views/homepage/_top_menu.html.haml
%ul.top_menu_bar{:type => 'none'}
  %li
    %a{:href => root_path}
      首页
  %li
    %a{:href => root_path}
      子页1
  %li
    %a{:href => root_path}
      子页2
  %li
    %a{:href => root_path}
      子页3
  %li
    %a{:href => root_path}
      子页4

app/views/homepage/show.html.haml
%button.enter_btn
  Enter
-#= form_for(url: query_infos_path, action: post) do |f|
-#  = f.label "Name"
-#  = f.label "Name"
-#  = f.text_field :people_name
-#  = f.submit "submit"

app/views/http_request/show.html.haml
= @response.body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LanSite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LanSite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= webpack_javascripts_tag 'pages.homepage' %>
  </head>

  <body>
    <%= render 'background' %>
    <%= yield %>
  </body>
</html>

app/views/query_infos/index.html.haml
.test
  This is query
= @query_infos